PB-580: add warning when leaving drawing mode without export or share
geoadmin/web-mapviewer pull request #1121
Opened 2024-11-08 09:31 UTC by sommerfe

2024-11-11 06:05 UTC, ltshb reviewed
Implementation looks just, just an issue regarding the store import.

Otherwise I think the warning message should be improved. @hansmannj 
 @Luke252 a warning about non exported drawing might be a good idea, but in my opinion the warning should say why we should export it or copy the share link. We should also differentiate if the drawing has only be shared via normal link without admin link.  So if the user don't click on export and/or copy admin link the warning should say that the drawing cannot be edited anymore once the webpage is reloaded !

2024-11-11 07:09 UTC, pakb reviewed
Implementation looks good, but I'm against this message.
It will confuse more than help IMHO.

2025-01-06 05:58 UTC, ltshb requested changes
I'm a bit lost here. The PR title says to add a warning when closing the drawing (as the code seems to do) but the warning is not added ? More over based on the previous comments on this PR we should not do it, if it has been decided to do it, it MUST BE documented in the PR. Finally looking at the ticket the changes required seems to have differ but are not 100% clear to me, @hansmannj @Luke252 What has been here decided ? We SHOULD document such decision in ticket. But I'm still quite against such warning, or it should provide a much better info to the user as simply "Attention, your drawing has not been shared.", because such warning is not useful for the purpose of the ticket. I mean maybe the user don't want to share it, but simply recover later on.

2025-01-09 09:50 UTC, ltshb reviewed
Found some issues while testing:
1. No warning set for subsequent drawing, here how to reproduce
  a. Create a drawing and save the admin link
  b. Close the drawing: no warning as expected because the admin link has been copied
  c. Delete the drawing
  d. Create a new drawing without copying the new admin link
  e. Close the new drawing -> no warning ! In this case the warning should come.
2. When copying the share link from the drawing, the crosshair param is added to the url (on current dev staging is not the case)

2025-01-09 09:50 UTC, ltshb commented on src/modules/i18n/locales/en.json
> +    "drawing_not_shared_admin_warning": "Attention, you have not generated a link to continue to edit your drawing. You won't be able to edit your drawing after closing this window.",
@Luke252 @hansmannj For all translation I would say `after reloading the website` instead of `closing this windows` (or something like this), because it is more correct, you can close the drawing and re-open it to get the admin link as long as you don't reload the page.

2025-01-09 13:52 UTC, hansmannj commented
> Found some issues while testing:
> 
> 1. No warning set for subsequent drawing, here how to reproduce
>    a. Create a drawing and save the admin link
>    b. Close the drawing: no warning as expected because the admin link has been copied
>    c. Delete the drawing
>    d. Create a new drawing without copying the new admin link
>    e. Close the new drawing -> no warning ! In this case the warning should come.
> 2. When copying the share link from the drawing, the crosshair param is added to the url (on current dev staging is not the case)

Good catch! :+1:

2025-01-09 13:59 UTC, hansmannj commented
Don't we also want to catch the case, where neither share nor admin link are copied and throw a corresponding warning then?

2025-01-09 14:01 UTC, hansmannj commented
> Don't we also want to catch the case, where neither share nor admin link are copied and throw a corresponding warning then?

Ah, ok, that seem's to be covered already, sorry!

2025-01-09 14:03 UTC, hansmannj commented on src/modules/i18n/locales/en.json
> +    "drawing_not_shared_admin_warning": "Attention, you have not generated a link to continue to edit your drawing. You won't be able to edit your drawing after closing this window.",
OK, my suggestion from above does not make much sense, since the admin link is already "thrown at the user" in this case, which makes sense.
So, yes, `after reloading the website` is fine for me!

2025-01-13 06:47 UTC, ltshb reviewed
You still have an issue when opening the share link of the drawing it adds the cross marker

![image](https://github.com/user-attachments/assets/6a1bd486-a975-459b-b863-bea47813a57a)

Other issues seems fine now

2025-01-15 18:35 UTC, ltshb approved these changes
Thanks

2025-01-16 07:38 UTC, merged