Pb 1213 polygon from line
geoadmin/web-mapviewer pull request #1177
Opened 2024-12-18 07:26 UTC by ismailsunni

2024-12-19 09:28 UTC, sommerfe approved these changes

2024-12-19 10:21 UTC, ltkum requested changes
There is currently an issue : if I try to extend a line other than the last line made, it will extend the last line made instead.

I'll provide a video as soon as I manage to get a capture working :)

2024-12-19 10:29 UTC, ltkum commented
https://github.com/user-attachments/assets/a476a784-c3d6-4342-8fb7-16d0dbf40d87

2024-12-30 04:40 UTC, ismailsunni commented
thanks @ltkum I have fixed it and add test to make sure it's fixed.

2025-01-06 09:53 UTC, ltkum reviewed
I would remove the debug logs before merging this. Otherwise this is good work, thanks.

2025-01-06 09:53 UTC, ltkum commented on tests/cypress/tests-e2e/drawing.cy.js
> +                    console.log(features)
This looks like debug logs.

If the logs are importants to use during tests, use cy.log and a small description of the content of the log.
If those are debug logs, you should remove them.

2025-01-06 09:53 UTC, ltkum commented on tests/cypress/tests-e2e/drawing.cy.js
> +                    })
this looks like this loop is only here for debug purposes. Same as above :)

2025-01-06 09:56 UTC, ltkum approved these changes

2025-01-06 14:50 UTC, pakb reviewed
tested it, works well, good work!
A couple questions, and some request for more JSDocs on the many composable used here and we should be good to go

2025-01-06 14:50 UTC, pakb commented on src/modules/drawing/components/DrawingInteractions.vue
> +        selectInteraction.value?.setActive(true)
`selectInteraction.value?.setActive(!selectedInteraction)`
could do the same, no?

2025-01-06 14:50 UTC, pakb commented on src/modules/drawing/components/DrawingInteractions.vue
> +let selectedLineFeature = null
you should make a `ref` out of this, as it might change without recreating the whole `useExtendLineInteraction` down the line

2025-01-06 14:50 UTC, pakb commented on src/modules/drawing/components/useExtendLineInteraction.composable.js
> +export default function useExtendLineInteraction({
please describe what are the input types in a JSDoc here

2025-01-06 14:50 UTC, pakb commented on src/modules/drawing/components/useDrawingModeInteraction.composable.js
> +    startingFeature = null,
might be good to also add some JSDoc on what types are expected here, it starts to get quite big...

2025-01-06 14:50 UTC, pakb commented on src/modules/drawing/components/ExtendLineInteraction.vue
> +    startingFeature: props.startingFeature,
I'm not sure it's a good idea to give that without wrapping it in a `ref`. The composable down the line isn't called once more when this value changes (if you select another line of the same drawing), so reactivity might be lost here.
But after testing, it seems to work fine...

2025-01-06 14:50 UTC, pakb commented on src/modules/drawing/components/useDrawingModeInteraction.composable.js
> +            nextTick().then(debounceSaveDrawing)
would a watch (deep watch if necessary) on the drawing layer also solve this issue?
Here you are waiting an arbitrary life cycle before committing to saving, but we can't be sure the next tick will be the one that has saved/stored everything you need, isn't it?

2025-01-06 23:22 UTC, ismailsunni commented on src/modules/drawing/components/DrawingInteractions.vue
> +        selectInteraction.value?.setActive(true)
yes :)

2025-01-06 23:58 UTC, ismailsunni commented on src/modules/drawing/components/ExtendLineInteraction.vue
> +    startingFeature: props.startingFeature,
I handled the selection in `DrawingInteractions.vue`, see [this](https://github.com/geoadmin/web-mapviewer/pull/1177/commits/7d885b6874f700975b888d9412697e03d9ade4a6#diff-6cb2ff831d9178e2c52712eb1b44e2437ba8c6b600351228eaed444ad8a13d3aR79-R91). Basically, if the feature selected is changed (from the select interaction) it will update the selectedLineFeature.

Or am I wrong?

2025-01-07 00:01 UTC, ismailsunni commented on src/modules/drawing/components/useDrawingModeInteraction.composable.js
> +            nextTick().then(debounceSaveDrawing)
It's not my original code actually. It's already there in develop branch, see [this](https://github.com/geoadmin/web-mapviewer/blob/develop/src/modules/drawing/components/useDrawingModeInteraction.composable.js#L189-L191). I only did a small refactor, i.e. put it in a if statement. So, I am not really sure what to do.

here is the original PR that introduce the code: https://github.com/geoadmin/web-mapviewer/pull/561/files#diff-3423e4552122109b2a6f9dac47e5d135482d4822ce8a85c113ec2c983463a51cR170-R172

2025-01-07 10:34 UTC, merged