BGDIINF_SB-2709 bugfix : drawings not interactive out of drawing mode
geoadmin/web-mapviewer pull request #343
Opened 2023-01-12 08:24 UTC by ltkum

Issue : user made kmls were not selectable outside the drawing mode
Fix : We made them selectable, and applied a read only property on them to hide the edition buttons, even if they were not usable outside the drawing mode.

2023-01-12 08:38 UTC, ltshb commented
The buttons in the combo are still visible 
![image](https://user-images.githubusercontent.com/67745584/212018236-3262c1ce-0b1c-4e53-89f5-512936b402d5.png)

2023-01-12 08:57 UTC, ltkum commented
I missed a small readOnly parameter at some place, thanks for catching it :)

2023-01-12 14:11 UTC, ltshb requested changes

2023-01-12 14:11 UTC, ltshb commented on src/store/plugins/click-on-map-management.plugin.js
> +            }
Could be done together in one if

2023-01-12 14:11 UTC, ltshb commented on src/store/plugins/click-on-map-management.plugin.js
> +                // TODO : kml popup / tooltip, how to find
REmove comment

2023-01-12 14:11 UTC, ltshb commented on src/store/plugins/click-on-map-management.plugin.js
> +                    log.debug("newly selected feature : ", newSelectedFeatures)
Remove debug

2023-01-12 14:11 UTC, ltshb commented on src/store/plugins/click-on-map-management.plugin.js
> +                    // stacktrace step 2
Remove debug

2023-01-12 14:24 UTC, pakb reviewed
a very nitpicky thing to add on top of Brice's comments 🙃

2023-01-12 14:27 UTC, pakb commented on src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
> +            id: this.layerId,
OL layer do have an idea, it's actually a good idea to set this value here (it is already done in other types of layers) it helps OL sort layers

2023-01-13 06:51 UTC, ltkum commented on src/store/modules/map.store.js
> +        click: ({ commit }, clickInfo) => commit('setClickInfo', clickInfo), // stack trace step 4
forgotten comment, I'll remove it

2023-01-13 07:07 UTC, ltkum commented on src/modules/map/components/openlayers/OpenLayersMap.vue
> +                            log.debug('Legacy KMLs are not supported for selection')
If the old kml is not an editable feature, it won't be possible to select it. I will change the debug message to reflect that.

2023-01-16 05:47 UTC, ltshb commented on src/modules/map/components/openlayers/OpenLayersKMLLayer.vue
> +            id: this.layerId,
Ok I did not found it in the docu of `VectorLayer`

2023-01-16 05:51 UTC, ltshb reviewed
Code looks good now, but you need to review you commit comments. Please make correct useful commit comments, you could probably reduce them to one comment.

2023-01-16 09:48 UTC, ltshb approved these changes

2023-01-16 19:32 UTC, merged