Little review on the current documentation
geoadmin/web-mapviewer pull request #8
Opened 2020-08-26 06:36 UTC by pakb

2020-08-26 08:37 UTC, ltshb requested changes
Looks good just a small changes about `secrets.yml` and some suggestions.

For new comer (like me) it would be good to have a link to `Vue` and `Vuex` in the `Project structure`  chapter.

In the `Project structure` a Folder tree image of the structure would help to understand it.

In chapter `Tooling for translation update` I would specify the gopass store name: `infra-gopass-bgdi`

2020-08-26 08:37 UTC, ltshb commented on README.md
> +The file `secrets.yml` will tell `gopass` which keys to get from the store.
Actually `secrets.yml` is used by summon not gopass. It does the mapping between the gopass key and the environment variable that should be exported

2020-08-27 05:45 UTC, pakb commented
Should be good, I've added what you suggested, thanks!

2020-08-27 05:53 UTC, ltshb approved these changes
:+1:

2020-08-27 06:57 UTC, merged