PB-750 : adapt CSS to enable browser print of the map
geoadmin/web-mapviewer pull request #992
Opened 2024-07-05 06:57 UTC by pakb

with only the layer attributions and eventual feature tooltip visible (no menu, no footer)

Had to adapt a bit the OpenLayerMouseTracker component so that it has a root HTML element (on which we can apply a class from the component using it)

2024-07-05 07:07 UTC, pakb commented
I will try to add the scale line too

2024-07-05 08:32 UTC, ltkum reviewed
When trying to print, it offers to print only the left quarter / half of the map. We might have to fiddle a bit more with the CSS to have a print layout which is correct, but we are heading in the right direction (on firefox by the way, in case this worked on other browsers)

for the following print attempt, it was from the default state of the application.

![image](https://github.com/geoadmin/web-mapviewer/assets/39826573/255fe3f8-b185-4f51-a639-071a3af3be01)

2024-07-08 05:25 UTC, ltshb requested changes

2024-07-08 05:25 UTC, ltshb commented on src/scss/webmapviewer-bootstrap-theme.scss
> +}
This is already present in main.scss which has been added for the tooltip print.

2024-07-08 05:25 UTC, ltshb commented on src/views/MapView.vue
> +        <LoadingBar v-show="showLoadingBar" class="no-print" />
You are breaking the tooltip print here, now with your change when you print the tooltip and you select the text in the tooltip you have part of the view that is printed invisible but selectable.
![image](https://github.com/geoadmin/web-mapviewer/assets/67745584/d8e19bc7-36c1-4112-85fe-dd22a0129f45)

2024-07-08 05:25 UTC, ltshb commented on src/views/MapView.vue
> +        <LoadingBar v-show="showLoadingBar" class="no-print" />
See https://github.com/geoadmin/web-mapviewer/pull/905/commits/e1875b1bdc72221295ce53f07d066d0feba08300 from #905

2024-09-19 08:05 UTC, pakb commented
Requires a ton of work to achieve a map print without breaking the tooltip print. I won't be pursuing this more, and focus on more pressing issues

2024-09-19 08:05 UTC, closed without merging